name: building and pushing image

on: push

env:
  GIT_REF=${{ steps.git.outputs }}
jobs:
  my-job:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checking out our code
      uses: actions/checkout@master
    - name: Output Git
      id: git
      run: |
        echo $(/usr/bin/git rev-parse HEAD)
        echo ${{ GIT_REF }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/website:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/website:v4.0
    

