name: building and pushing image

on: push

jobs:
  my-job:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checking out our code
      uses: actions/checkout@master
    - run: pwd
    - run: ls
    - name: docker login
      run: docker login ${{ secrets.DOCKER_HUB_USERNAME }} ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    

