name: building and pushing image

on: push

jobs:
  my-job:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker Build and Push
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/website:latest
